theme: minima
title: The Reflecting Pool
author: John Epling
description: There is an art of which every man should be a master – the art of reflection. If you are not a thinking man, to what purpose are you a man at all? – William Hart Coleridge
